global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hair-style-web'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:5000']

